version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose the frontend on port 80

  # backend:
  #   image: node:14  # Replace with your backend image
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./path/to/backend:/usr/src/app  # Mount the backend code
  #   working_dir: /usr/src/app
  #   command: node index.js  # Replace with your backend start command
  #   ports:
  #     - "3000:3000"  # Expose the backend on port 3000
